title: Short Scoop
author: 
description:

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: 
plugins:
collections:
   pages:
      output: true
      permalink: /:name